name: tgif_clisops
channels:
 - conda-forge
dependencies:
 - python >=3.9,<3.13
 - pip
 - flit
 - bottleneck >=1.3.1
 - cartopy >=0.23.0
 - cf_xarray >=0.8.6
 - cftime >=1.4.1
 - dask >=2.6.0
 - gdal >=3.0
 - geopandas >=0.11
 - loguru >=0.5.3
 - netCDF4 >=1.4
 - numpy >=1.16,<2.1
 - packaging
 - pandas >=1.0.3
 - platformdirs >=4.0
 - pooch
 - poppler >=0.67
 - pyproj >=3.3.0
 - requests >=2.0
 - roocs-grids >=0.1.2
 - roocs-utils >=0.6.7,<0.7
 - shapely >=1.9
 - xarray ==2023.2.0 # See: https://github.com/pydata/xarray/issues/7794
 - xesmf >=0.8.2
  # Dev tools and testing
 - black >=24.1.0
 - bump-my-version >=0.17.1
 - flake8
 - gitpython >=3.1.30
 - ipython
 - isort
 - jinja2 >=2.11
 - pre-commit >=3.0.0
 - pytest
 - pytest-cov
 - pytest-loguru >=0.3.0
 - tox >=4.0
 - watchdog
 # Documentation
 - ipykernel
 - ipython
 - ipython_genutils
 - jupyter_client
 - jupyterlab
 - matplotlib >=3.5.2
 - nbsphinx
 - pandoc
 - sphinx
 - sphinx-rtd-theme >=1.0
 #- clisops>=0.7.0
 - pip:
     - clisops @ git+https://github.com/roocs/clisops/@regrid_masks_and_fixes#egg=clisops
     - psy-maps
